name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m test_main


      
      - name: Set up Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo "${{ secrets.HEROKU_API_KEY }}" | heroku login --interactive

      - name: Build and push Docker image
        run: heroku container:push web --app liam-blog-app

      - name: Release Docker image
        run: heroku container:release web --app liam-blog-app

