name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests -p 'test_*.py'

      - name: Login to Heroku
        run: heroku container:login

      - name: Build and push Docker image
        run: heroku container:push web --app your-heroku-app-name

      - name: Release Docker image
        run: heroku container:release web --app liam-blog-app
